# The URL the site will be built for
# base_url = "https://dzikri.my.id"
base_url = "https://stunning-profiterole-6d8f0b.netlify.app"

title="Dzikri"
description="This blog is my space to share knowledge dan experinces."


# The site theme to use.
theme = "kita"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

#[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
#highlight_code = false

#[extra]
# Put all your custom variables here
#generate_feeds = true

# The filenames to use for the feeds. Used as the template filenames, too.
# Defaults to ["atom.xml"], which has a built-in template that renders an Atom 1.0 feed.
# There is also a built-in template "rss.xml" that renders an RSS 2.0 feed.
feed_filenames = ["atom.xml"]

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = [{ name = "tags", rss = true, paginate_by = 5 }]

# Configuration of the Markdown rendering
[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true

# A list of directories used to search for additional `.sublime-syntax` and `.tmTheme` files.
extra_syntaxes_and_themes = []

# The theme to use for code highlighting.
# See below for list of allowed values.
highlight_theme = "base16-ocean-dark"

# The Kita theme style config.
[extra]
# Enable KaTex math formula support globally.
math = false
# Enable mermaid support globally.
mermaid = false
# Enable comment support globally.
comment = false
# The URL of social image.
social_image = "icons/github.svg"

[extra.style]
# The custom background color.
# bg_color = ""

# The custom background color in dark mode.
# bg_dark_color = ""

# Enable header blur.
# header_blur = true

# The custom header color, only available when `header_blur` is false.
# header_color = ""

# The custom header color in dark mode, only available when `header_blur` is false.
# header_dark_color = ""

# The profile on home page.
[extra.profile]
name = "Dzikri Hakim"
bio = "Muslem | Pythonista | Data Enthusiast | Analytics | Productivity  "
# The URL of avatar.
avatar_url = "icons/prodz.svg"
# Invert color in dark mode.
avatar_invert = true

# The social icons below the profile on the home page.
# The `name` should be the file name of static/icons/*.svg or the icon name of https://simpleicons.org/
[[extra.profile.social]]
name = "github"
url = "https://github.com/dzikrihak"

[[extra.profile.social]]
name = "twitter"
url = "https://github.com/dzhakim"

[[extra.profile.social]]
name = "rss"
url = "$BASE_URL/atom.xml"

[[extra.profile.social]]
name = "instagram"
url = "https://instagram.com/dzikrihak"

[[extra.profile.social]]
name = "linkedin"
url = "https://linkedin.com/dzikrihak"







# The top menu.
[[extra.menu]]
name = "Projects"
url = "$BASE_URL/projects"

[[extra.menu]]
name = "Archive"
url = "$BASE_URL/archive"

[[extra.menu]]
name = "Tags"
url = "$BASE_URL/tags"

[[extra.menu]]
name = "About"
url = "$BASE_URL/about"

# The page footer options.
[extra.footer]
#since = 
license = "CC BY-SA 4.0"
license_url = "https://creativecommons.org/licenses/by-sa/4.0/deed"

# The giscus comment options, only available when comment is enabled.
[extra.giscus]
repo = ""
repo_id = ""
category = ""
category_id = ""
mapping = "pathname"
strict = 1
reactions_enabled = 0
emit_metadata = 0
input_position = "top"
theme = "light"
lang = "en"
loading = "lazy"
